<a href="https://colab.research.google.com/github/sourabhpatange11/Multiclass_Classification-/blob/main/Multiclass_Classification_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving iris.csv to iris.csv
User uploaded file "iris.csv" with length 3858 bytes


In [2]:
import pandas as pd
import io

In [3]:
Data = pd.read_csv('iris.csv')
Data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
Data.shape

(150, 5)

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import adam_v2
import pydot
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils.vis_utils import plot_model
import graphviz
import numpy as np
import seaborn as sns

In [6]:
X= Data.iloc[:,0:4].values
y= Data.iloc[:,4].values

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1= encoder.fit_transform(y)
Y=pd.get_dummies(y1).values

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [9]:
X_train

array([[5. , 3.5, 1.3, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [5.2, 3.5, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [4.8, 3.1, 1.6, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5. , 2. , 3.5, 1. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.4, 3.9, 1.7, 0.4],
       [5.7, 2.9, 4.2, 1.3],
       [4.8, 3.4, 1.9, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 3.4, 5.4, 2.3],
       [6. , 2.2, 5. , 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 3. , 1.6, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.4, 3.4, 1.5, 0.4],
       [6. , 3. , 4.8, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6.1, 2.8, 4. , 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [5.8, 4. , 1.2, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [5.7, 2.5, 5. , 2. ],
       [4.8, 3

In [10]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [23]:
model = Sequential()

#Adding hidden layer

model.add(Dense(units=4,activation = 'relu',input_dim =4))

#adding output layer
model.add(Dense(units=3  ,activation='softmax'))

#softmax activation function is used in multiclass classification

In [24]:
#Compiling Model

model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])


#loss =categorical_crossentropy used for categorical data 

In [25]:
model.fit(X_train,y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 2.2011 - accuracy: 0.3417
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 2.0545 - accuracy: 0.3417
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 1.9213 - accuracy: 0.3417
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 1.7975 - accuracy: 0.3417
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 1.6688 - accuracy: 0.3417
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 1.5558 - accuracy: 0.3417
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 1.4411 - accuracy: 0.3417
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.3388 - accuracy: 0.3417
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 1.2397 - accuracy: 0.3417
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.1583 - accuracy: 0.3417
Epoch 11/

In [26]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred, axis = 1)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.92      0.96        12
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[ 9  0  0]
 [ 0 11  1]
 [ 0  0  9]]


In [28]:
(9+11+9)/30   #for checking accuracy

0.9666666666666667